# Site settings
title: Jour71105
description: '<p>Multimedia Interactive</p><hr><p><a href="/jour71105/tk/">tk</a><br><a href="/jour71105/tk/">tk</a><br><a href="/jour71105/tk/">tk</a></p><hr><p><a href="/jour71105/tk/">tk</a><br><a href="/jour71105/tk/">tk</a><br><a href="/jour71105/tk/">tk</a></p>'
url: https://mrsingleton.github.io
theme: jekyll-theme-minimal
email: mrsingleton@gmail.com
keywords: "cuny interactive, cuny journalism, newmark school, course website, malik singleton, digital storytelling, data journalism, infographics, data visualization"
skills: "Data Science - Web Development - Information Architecture - User Experience"
meta_author: Singleton Malik
